### ISSUE TITLE
Some inadequate statements; fix needed.

### ISSUE THREAD

**Issue by mu578** [FermiDirak/fermidirak.github.io#1]
`-- have lead the development of a core embedded machine learning library`

`++ I participated in the development of a embedded ML framework ; mostly by adapting  and sketching a SVM algorithm using the Sequential minimal optimization method (1) (in almost C99).`

- (1) John Platt in 1998 at Microsoft Research.

**Comment by FermiDirak** [comment]
Made a change on my main bio to better reflect that I had ownership of only one module of the ML library. Don't want to take credit for the entire thing :P You're the actual leader of the project 👍 

Also added the citation to my work experience page :D 

`-- have lead the development of a core embedded machine learning library`
`++have lead the development of a core embedded machine learning library module`


`--<li>Developed a C implementation of Support Vector Machines Classifier for embedded systems</li>`

`++     <li>Participated in the development of an embedded machine learning framework</li>
        <li>Implemented in ansi C99 <a href="https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr-98-14.pdf">John Platt's SMO Support Vector Machines Classifier</a> for embedded systems</li>`

**Comment by mu578** [comment]
Good evening,

sorry for the late answer but I must correct some statements ; even if I occupied (and still occupy) a position of leadership with Aerendir ; for what is the ML concerns Nicolas is the true architect ; I just help him the best I could to achieve what he had in mind as always.

BTW you could have told me, instead of running away mad.
